### ISSUE TITLE
how can i use your method , please ? 

### ISSUE THREAD

**Issue by mathshangw** [jungokasai/THumB#2]
I'm interested in your paper, but please how can I use your method to evaluate my captions?

**Comment by jungokasai** [comment]
Apologies for my response. Thank you for your interest in our work! 
Our work conducts expert human evaluations, but you can submit your MSCOCO captions here: https://nlp.cs.washington.edu/billboard/#submit.html. 
[Our followup work](https://arxiv.org/abs/2112.04139) provides a leaderboard that automatically computes state-of-the-art automated evaluations, including [CLIPScore](https://arxiv.org/abs/2104.08718).
